spring.application.name=MineProjeto


spring.datasource.username=postgres
spring.datasource.password=Lipegtj2009@
spring.datasource.url=jdbc:postgresql://localhost:5432/LojaJPA

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true